- name: Configure kernel modules
  copy:
      dest: /etc/modules-load.d/containerd.conf
      content: |
        {% for module in enable_kernel_modules -%}
          {{ module }}
        {% endfor %}

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ enable_kernel_modules }}"

- name: Enable kernel parameters
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  loop: "{{ enable_kernel_parameters }}"
