- name: Install the crictl config file
  copy:
      dest: /etc/crictl.yaml
      content: |
        runtime-endpoint: unix:///run/containerd/containerd.sock
        image-endpoint: unix:///run/containerd/containerd.sock

################################################################################
# Grant the vagrant user access to crictl
################################################################################

- name: Create a group for containerd access
  group:
    name: containerd
    state: present

- name: Add the vagrant user to the containerd group
  user:
    name: vagrant
    groups: containerd
    append: yes

- name: Set group ownership of /run/containerd/containerd.sock to containerd
  file:
    path: /run/containerd/containerd.sock
    group: containerd
