- name: Add repository keys
  apt_key:
    url: "{{item.key}}"
  with_items: "{{ package_keys | default([])}}"
  when: package_keys is defined and not (package_keys is none or package_keys | trim == '')
  register: apt_keys

- name: Add repositories
  apt_repository:
    repo: "{{item.repo}}"
  with_items: "{{ package_repositories | default([])}}"
  when: package_repositories is defined and not (package_repositories is none or package_repositories | trim == '')

- name: Update apt cache
  set_fact:
    package_cache_valid_time: 0
  when: apt_keys.changed

- name: Install general packages
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{package_cache_valid_time}}"
  with_items: "{{ general_package_names | default([])}}"
  when: general_package_names is defined and not (general_package_names is none or general_package_names | trim == '')
