- name: "Install Kubernetes packages"
  apt:
    name: "{{ item }}={{ kubernetes_version }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ package_cache_valid_time }}"
  with_items: "{{ kubernetes_package_names }}"

- name: Configure kubelet service
  lineinfile:
    path: "/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf"
    line: 'Environment="KUBELET_EXTRA_ARGS=--node-ip={{ public_ip }}"'
    regexp: "KUBELET_EXTRA_ARGS="
    insertafter: "[Service]"
    state: present
  register: kubelet_config

- name: Trigger systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: Restart kubelet service
  systemd:
    state: restarted
    name: kubelet
  when: kubelet_config.changed
