- name: "Download containerd"
  get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
    dest: /tmp/containerd.tar.gz

- name: Extract the containerd binary
  unarchive:
    src: /tmp/containerd.tar.gz
    remote_src: yes
    dest: /usr/local

- name: Remove the containerd download
  file:
    path: /tmp/containerd.tar.gz
    state: absent

- name: Create a default containerd config
  shell: containerd config default
  register: containerd_config

- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Save containerd config to file
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml

- name: Update the containerd config file
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup \= false'
    line: 'SystemdCgroup = true'

- name: Download the systemd service config for containerd
  get_url:
    url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
    dest: /etc/systemd/system/containerd.service

- name: Trigger systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: Enable and start the containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started
