- name: "Install Kubernetes packages ({{ kubernetes_version }})"
  apt:
    name: "{{ item.name }}={{ kubernetes_version }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{package_cache_valid_time}}"
  with_items: "{{ kubernetes_package_names | default([])}}"
  when: kubernetes_package_names is defined and not (kubernetes_package_names is none or kubernetes_package_names | trim == '')

- name: Configure kubelet service
  lineinfile:
    path: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    line: 'Environment="KUBELET_EXTRA_ARGS=--node-ip={{ public_ip }}"'
    regexp: "KUBELET_EXTRA_ARGS="
    insertafter: "[Service]"
    state: present
  register: kubelet_config

- name: Restart kubelet service
  systemd:
    state: restarted
    name: kubelet
  when: kubelet_config.changed
