- name: Create directory /home/vagrant/.kube
  file:
    path: "/home/vagrant/.kube"
    owner: vagrant
    group: vagrant
    state: directory

- name: Copy kube config to /home/vagrant/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest:  /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: 0600

- name: Create directory /root/.kube
  file:
    path: "/root/.kube"
    state: directory

- name: Copy kube config to /root/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest:  /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: 0600

- name: Copy kube config to local file
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ../kubeconfig
    flat: yes
