- name: Create cilium namespace
  kubernetes.core.k8s:
    server_side_apply:
      field_manager: ansible
    name: cilium
    api_version: v1
    kind: Namespace
    state: present

- name: Add cilium helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io

- name: "Install cilium helm chart ({{ cilium_version }})"
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_version }}"
    release_namespace: cilium
    wait: no
